Repository wooahan-agile/idu-market-next, pull requests merged in 2021-05, with the labels that each got.

#19 Add(minjae/boardDelete): board Delete, S3 image Delete #16
  app/components/Board/BoardDetailTop.js
  app/components/Header/Header.js
  app/redux/reducers/boardReducer.js
  app/redux/sagas/boardSaga.js
  app/redux/types.js
Labels: Next, Redux

#22 [boardUpdate]Board update
  Dockerfile
  app/components/Board/Basic.js
  app/components/Comment/Comment.js
  app/components/Editor/Editor.js
  app/components/Editor/EditorImageUpload.js
  app/components/Editor/EditorPost.js
  app/components/Editor/UpdateEdtior.js
  app/components/Header/Header.js
  app/scss/layout/_header.scss
  app/scss/layout/board/_boardDetailImage.scss
Labels: Next, Redux, 스타일링

#35 [tradeComplete] Trade Complete
  app/components/Comment/ReplyComment.js
  app/components/Comment/SingleComment.js
  app/components/Trade/TradeComplete.js
  app/pages/watchlist/[studentId].js
  app/redux/sagas/boardSaga.js
  app/redux/sagas/tradeSaga.js
  app/scss/layout/_header.scss
  app/scss/layout/board/_boardDetailImage.scss
  app/scss/layout/home/_notice.scss
Labels: Next, Redux

#40 [purchaseList] Purchase List
  app/pages/purchase-list/[studentId].js
  app/scss/layout/board/_market.scss
Labels: Next, Redux, 스타일링

#42 [header] Header
  app/Data/HeaderMenuData.js
  app/components/Header/Header.js
  app/pages/findPwd.js
  app/scss/layout/_header.scss
Labels: Next, Redux, 스타일링

#44 [404page] 404Page
  app/pages/404.js
  app/scss/main.scss
  app/scss/page/_page404.scss
Labels: Next, 스타일링

#46 [inquiryReceive] Inquiry Receive
  app/Data/HeaderMenuData.js
  app/Data/MajorData.js
  app/components/Editor/Editor.js
  app/components/Profile/ProfileContent.js
  app/components/Profile/ProfileUpdate.js
  app/components/Service/Inquiry.js
  app/pages/register.js
  app/pages/service/inquiry.js
  app/redux/reducers/authReducer.js
  app/scss/helpers/_variables.scss
  app/scss/layout/service/_inquiry.scss
  app/scss/main.scss
  app/scss/page/_404.scss
Labels: Next, 스타일링

#48 [pwdChange] Pwd Change
  app/components/Auth/FindIdForm.js
  app/components/Auth/FindPwdForm.js
  app/components/Auth/LoginForm.js
  app/components/Auth/PwdResetForm.js
  app/components/Auth/RegisterForm.js
  app/pages/api/hello.js
  app/pages/boards/[categoryName]/[num].js
  app/pages/findId.js
  app/pages/findPwd.js
  app/pages/login.js
  app/pages/register.js
  app/pages/reset/password/[token].js
Labels: Next, Redux, 스타일링

#50 [notification] Notification
  app/components/Comment/Comment.js
  app/components/Comment/SingleComment.js
  app/components/Trade/TradeComplete.js
  app/redux/reducers/authReducer.js
  app/redux/reducers/index.js
  app/redux/reducers/notificationReducer.js
  app/redux/sagas/index.js
  app/redux/sagas/notificationSaga.js
  app/redux/types.js
Labels: Next, Redux, 스타일링

#52 Fix(sangjun/admin): 게시글 리트스 관리자 색 변경, basic게시판 font변경 #51
  app/components/Board/Basic.js
  app/components/Board/BoardDetailTop.js
  app/components/Board/MarketListItem.js
  app/components/Comment/ReplyComment.js
  app/components/Comment/SingleComment.js
  app/package-lock.json
  app/scss/layout/board/_basic.scss
  app/scss/layout/board/_boardDetail.scss
  app/scss/layout/board/_comment.scss
  app/scss/layout/board/_market.scss
Labels: Next, 스타일링

#53 [notification]Notification
  app/components/Board/MarketListItem.js
  app/components/Comment/Comment.js
  app/components/Comment/SingleComment.js
  app/components/Editor/Editor.js
  app/components/Header/Header.js
  app/components/Notification/Notification.js
  app/components/Trade/TradeComplete.js
  app/pages/boards/[categoryName]/new.js
  app/redux/reducers/notificationReducer.js
  app/redux/sagas/commentSaga.js
  app/redux/sagas/notificationSaga.js
  app/redux/sagas/tradeSaga.js
  app/redux/types.js
  app/scss/layout/board/_basic.scss
  app/scss/layout/board/_comment.scss
  app/scss/layout/board/_market.scss
  app/scss/layout/home/_mainBanner.scss
  app/scss/layout/notification/_notification.scss
  app/scss/main.scss
Labels: Next, Redux, 스타일링

#55 [editor] Editor issue fix
  app/components/Board/Basic.js
  app/components/Board/BoardDetailImage.js
  app/components/Editor/Editor.js
  app/components/Editor/UpdateEdtior.js
  app/pages/boards/[categoryName]/[num].js
Labels: Next, 스타일링

#57 [validation] Validation
  app/components/Board/Basic.js
  app/components/Board/BoardDetailTop.js
  app/components/Board/BoardListItem.js
  app/components/Board/Market.js
  app/components/Board/MarketListItem.js
  app/components/Notification/Notification.js
  app/pages/purchase-list/[studentId].js
  app/pages/sale-list/[studentId].js
  app/pages/watchlist/[studentId].js
  app/redux/sagas/boardSaga.js
  app/redux/sagas/notificationSaga.js
  app/scss/components/board/_basic.scss
  app/scss/components/board/_boardDetail.scss
  app/scss/components/board/_boardDetailImage.scss
  app/scss/components/board/_boardWrite.scss
  app/scss/components/board/_market.scss
  app/scss/components/comment/_comment.scss
  app/scss/components/notification/_notification.scss
  app/scss/components/profile/_profile.scss
  app/scss/components/profile/_profileUpdate.scss
  app/scss/components/service/_inquiry.scss
  app/scss/components/trade/_tradeComplete.scss
  app/scss/components/watchlist/_watchlist.scss
  app/scss/main.scss
Labels: Next, Redux, 스타일링

#58 [notification] Notification
  app/components/Notification/Notification.js
  app/components/Notification/NotificationItem.js
  app/scss/components/notification/_notification.scss
Labels: Next, 스타일링

#60 [admin] Admin
  app/components/Board/Basic.js
  app/components/Board/BoardDetailTop.js
  app/components/Board/Market.js
  app/components/Board/MarketListItem.js
  app/components/Comment/Comment.js
  app/components/Comment/ReplyComment.js
  app/components/Comment/SingleComment.js
  app/components/Editor/Editor.js
  app/components/Editor/EditorConfig.js
  app/redux/sagas/authSaga.js
  app/redux/sagas/boardSaga.js
  app/redux/sagas/commentSaga.js
  app/redux/sagas/tradeSaga.js
  app/scss/components/board/_basic.scss
  app/scss/components/board/_market.scss
  app/scss/components/comment/_comment.scss
  app/scss/components/notification/_notification.scss
Labels: Next, Redux, 스타일링

#62 [layout] Layout
  app/components/Auth/RegisterForm.js
  app/components/HomePage/Function.js
  app/components/HomePage/Introduce.js
  app/components/HomePage/MainBanner.js
  app/scss/components/board/_basic.scss
  app/scss/components/board/_market.scss
  app/scss/components/notification/_notification.scss
  app/scss/components/profile/_profile.scss
  app/scss/components/service/_inquiry.scss
  app/scss/components/watchlist/_watchlist.scss
  app/scss/layout/_forms.scss
  app/scss/layout/home/_articles.scss
  app/scss/layout/home/_funtion.scss
  app/scss/layout/home/_introduce.scss
  app/scss/layout/home/_mainBanner.scss
  app/scss/layout/home/_notice.scss
Labels: Next, 스타일링

#65 [loading]Loading
  app/components/Board/Basic.js
  app/components/Board/Market.js
  app/components/Editor/Editor.js
  app/components/Editor/UpdateEdtior.js
  app/components/HomePage/Articles.js
  app/components/HomePage/Function.js
  app/components/HomePage/Introduce.js
  app/components/Loading/Loading.js
  app/pages/_app.js
  app/pages/boards/[categoryName]/[num].js
  app/pages/index.js
  app/redux/reducers/boardReducer.js
  app/redux/reducers/tradeReducer.js
  app/scss/components/comment/_comment.scss
  app/scss/components/loading/_loading.scss
  app/scss/layout/_header.scss
  app/scss/layout/home/_articles.scss
  app/scss/main.scss
Labels: Next, Redux, 스타일링

#66 [studentId] 로그인, 회원가입 수정 #64
  app/Data/MajorData.js
  app/components/Auth/FindPwdForm.js
  app/components/Auth/LoginForm.js
  app/components/Auth/PwdResetForm.js
  app/components/Auth/RegisterForm.js
  app/components/Profile/ProfileUpdate.js
  app/pages/findId.js
  app/pages/findPwd.js
  app/pages/register.js
Labels: Next, 스타일링

#71 [meta]Meta
  app/Data/NoticeSliderData.js
  app/components/HomePage/Notice.js
  app/pages/_document.js
  app/scss/components/watchlist/_watchlist.scss
  app/scss/layout/home/_notice.scss
Labels: Next, 스타일링

#73 [errorFix] Error Fix
  app/components/Header/Header.js
  app/components/Notification/Notification.js
  app/components/Notification/NotificationItem.js
  app/scss/components/notification/_notification.scss
Labels: Error, Next

#74 Error fix
  app/Data/MajorData.js
  app/components/Comment/Comment.js
  app/components/Comment/SingleComment.js
  app/components/Editor/Editor.js
  app/components/Editor/UpdateEdtior.js
  app/components/Trade/TradeComplete.js
  app/redux/sagas/commentSaga.js
  app/redux/sagas/tradeSaga.js
  app/scss/components/comment/_comment.scss
Labels: Error, Next

#76 [error] Error
  app/components/Board/BoardDetailTop.js
  app/components/Comment/ReplyComment.js
  app/components/Comment/SingleComment.js
  app/components/Editor/Editor.js
  app/components/Editor/UpdateEdtior.js
  app/components/Trade/TradeComplete.js
  app/pages/purchase-list/[studentId].js
  app/redux/reducers/boardReducer.js
  app/redux/reducers/notificationReducer.js
  app/redux/sagas/notificationSaga.js
  app/redux/sagas/tradeSaga.js
  app/redux/types.js
Labels: Error, Next, Redux
