Repository wooahan-agile/idu-market-next, pull requests merged in 2021-07, with the labels that each got.

#86 [api] 모든 API요청 헤더에 api-key추가
  app/components/Board/BoardDetailImage.js
  app/components/Editor/Editor.js
  app/components/Editor/EditorImageUpload.js
  app/components/Editor/UpdateEdtior.js
  app/components/Profile/ProfileUpdate.js
  app/pages/boards/[categoryName]/[num].js
  app/pages/boards/book.js
  app/pages/boards/clothes.js
  app/pages/boards/device.js
  app/pages/boards/etc.js
  app/pages/boards/free.js
  app/pages/boards/notice.js
  app/pages/findId.js
  app/pages/findPwd.js
  app/pages/login.js
  app/pages/purchase-list/[studentId].js
  app/pages/register.js
  app/pages/reset/password/[token].js
  app/pages/sale-list/[studentId].js
  app/pages/watchlist/[studentId].js
  app/redux/reducers/boardReducer.js
  app/redux/sagas/authSaga.js
  app/redux/sagas/boardSaga.js
  app/redux/sagas/commentSaga.js
  app/redux/sagas/notificationSaga.js
  app/redux/sagas/profileSaga.js
  app/redux/sagas/tradeSaga.js
Labels: Next, Redux

#88 [api] 모든 API 헤더 api-key값 추가
  app/Data/API_KEY.js
  app/components/Editor/Editor.js
  app/components/Editor/EditorImageUpload.js
  app/components/Editor/UpdateEdtior.js
  app/components/Profile/ProfileUpdate.js
  app/package-lock.json
  app/package.json
  app/pages/boards/[categoryName]/search.js
  app/pages/boards/book.js
  app/pages/boards/clothes.js
  app/pages/boards/device.js
  app/pages/boards/etc.js
  app/pages/boards/free.js
  app/pages/boards/notice.js
  app/pages/findId.js
  app/pages/findPwd.js
  app/pages/login.js
  app/pages/purchase-list/[studentId].js
  app/pages/register.js
  app/pages/reset/password/[token].js
  app/pages/watchlist/[studentId].js
  app/redux/sagas/authSaga.js
  app/redux/sagas/boardSaga.js
  app/redux/sagas/commentSaga.js
  app/redux/sagas/notificationSaga.js
  app/redux/sagas/profileSaga.js
  app/redux/sagas/tradeSaga.js
Labels: Error, Next

#91 Fix(sangjun/register): 회원가입 정구식 및 에레머시지 수정 #90
  Dockerfile
  app/Data/API_KEY.js
  app/components/Auth/RegisterForm.js
  app/components/Board/Basic.js
  app/components/Board/BoardDetailImage.js
  app/components/Board/Market.js
  app/components/Editor/Editor.js
  app/components/Editor/EditorImageUpload.js
  app/components/Editor/EditorPost.js
  app/components/Editor/UpdateEdtior.js
  app/components/HomePage/Articles.js
  app/components/HomePage/MainBanner.js
  app/components/Profile/ProfileUpdate.js
  app/package-lock.json
  app/package.json
  app/pages/_document.js
  app/pages/boards/[categoryName]/[num].js
  app/pages/boards/[categoryName]/[num]/update.js
  app/pages/boards/[categoryName]/search.js
  app/pages/boards/book.js
  app/pages/boards/clothes.js
  app/pages/boards/device.js
  app/pages/boards/etc.js
  app/pages/boards/free.js
  app/pages/boards/notice.js
  app/pages/findId.js
  app/pages/findPwd.js
  app/pages/login.js
  app/pages/purchase-list/[studentId].js
  app/pages/register.js
  app/pages/reset/password/[token].js
  app/pages/sale-list/[studentId].js
  app/pages/watchlist/[studentId].js
  app/public/robots.txt
  app/public/sitemap.xml
  app/redux/reducers/boardReducer.js
  app/redux/sagas/authSaga.js
  app/redux/sagas/boardSaga.js
  app/redux/sagas/commentSaga.js
  app/redux/sagas/notificationSaga.js
  app/redux/sagas/profileSaga.js
  app/redux/sagas/tradeSaga.js
Labels: Error, 스타일링

#92 [register] 회원 가입 인풋 오류시 동작하는 handler 추가
  app/components/Auth/RegisterForm.js
  app/pages/register.js
Labels: Error, Next

#94 Modify(sagnjun/image): NHN 이미지삭제 기능구현#93
  app/components/Board/BoardDetailTop.js
  app/pages/boards/[categoryName]/[num].js
  app/redux/sagas/boardSaga.js
Labels: Next, Redux

#96 [mainPage] MainPage UI 수정
  app/components/Footer/Footer.js
  app/components/HomePage/Articles.js
  app/components/HomePage/Circles.js
  app/components/HomePage/Function.js
  app/components/HomePage/Introduce.js
  app/components/HomePage/MainBanner.js
  app/components/HomePage/Notice.js
  app/pages/index.js
  app/scss/layout/_footer.scss
  app/scss/layout/home/_articles.scss
  app/scss/layout/home/_circles.scss
  app/scss/layout/home/_funtion.scss
  app/scss/layout/home/_introduce.scss
  app/scss/layout/home/_mainBanner.scss
  app/scss/layout/home/_notice.scss
  app/scss/main.scss
Labels: Next, 스타일링

#97 [mainPage] Main Page
  app/Data/NoticeSliderData.js
  app/components/HomePage/Articles.js
  app/components/HomePage/Circles.js
  app/components/HomePage/Function.js
  app/components/HomePage/Introduce.js
  app/components/HomePage/MainBanner.js
  app/components/HomePage/Notice.js
  app/package.json
  app/pages/index.js
  app/scss/common/_swiper.scss
  app/scss/layout/home/_articles.scss
  app/scss/layout/home/_circles.scss
  app/scss/layout/home/_funtion.scss
  app/scss/layout/home/_introduce.scss
  app/scss/layout/home/_mainBanner.scss
  app/scss/layout/home/_notice.scss
  app/scss/main.scss
  app/yarn.lock
Labels: 스타일링

#98 [mainPage] Main page UI 수정
  app/components/Board/BoardListTop.js
  app/components/Board/Market.js
  app/scss/components/board/_market.scss
  app/scss/layout/_header.scss
  app/scss/layout/board/_boardBanner.scss
  app/scss/layout/home/_articles.scss
  app/scss/layout/home/_circles.scss
  app/scss/layout/home/_funtion.scss
  app/scss/layout/home/_introduce.scss
  app/scss/layout/home/_mainBanner.scss
  app/scss/layout/home/_notice.scss
Labels: Next
