Repository wooahan-agile/idu-market-next, pull requests merged in 2021-08, with the labels that each got.

#102 Add(sangjun/freemarket):무료나눔 게시판 추가 #101
  app/Data/HeaderMenuData.js
  app/package-lock.json
  app/pages/boards/freemarket.js
Labels: Next

#104 [boards]Boards
  app/pages/boards/[categoryName]/[num].js
  app/pages/boards/[categoryName]/[num]/update.js
  app/pages/boards/book.js
  app/pages/boards/clothes.js
  app/pages/boards/device.js
  app/pages/boards/etc.js
  app/pages/boards/free.js
  app/pages/boards/notice.js
  app/pages/login.js
  app/redux/sagas/boardSaga.js
  app/scss/layout/_header.scss
Labels: Next

#107 Fix(sangjun/status): 무료나눔 게시판 거래상태 수정#106
  app/pages/boards/[categoryName]/[num]/[studentId]/complete.js
Labels: Error

#109 [boardDetail] Board detail
  app/components/Board/BoardDetailImage.js
  app/components/Board/BoardDetailTop.js
  app/components/HomePage/Notice.js
  app/pages/_app.js
  app/pages/boards/[categoryName]/[num].js
  app/scss/common/_swiper.scss
  app/scss/components/board/_boardDetail.scss
  app/scss/components/board/_boardDetailImage.scss
Labels: Next, 스타일링

#111 [axios] Axios Default 설정
  app/components/Editor/Editor.js
  app/components/Profile/ProfileUpdate.js
  app/components/Service/Inquiry.js
  app/components/Trade/TradeComplete.js
  app/pages/_app.js
  app/pages/boards/[categoryName]/search.js
  app/pages/boards/book.js
  app/pages/boards/clothes.js
  app/pages/boards/device.js
  app/pages/boards/etc.js
  app/pages/boards/free.js
  app/pages/boards/freemarket.js
  app/pages/boards/notice.js
  app/pages/findId.js
  app/pages/findPwd.js
  app/pages/login.js
  app/pages/purchase-list/[studentId].js
  app/pages/register.js
  app/pages/reset/password/[token].js
  app/pages/sale-list/[studentId].js
  app/pages/watchlist/[studentId].js
  app/redux/sagas/authSaga.js
  app/redux/sagas/boardSaga.js
  app/redux/sagas/commentSaga.js
  app/redux/sagas/notificationSaga.js
  app/redux/sagas/profileSaga.js
  app/redux/sagas/tradeSaga.js
Labels: Next, Redux
